
# Continuous Integration
name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      uses: actions/checkout@v4

    # ================================
    # VALIDATE GRADLE WRAPPER
    # ================================
    - name: Validate Gradle Wrapper files
      uses: gradle/actions/wrapper-validation@v3

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 21

    # ================================
    # SET UP GRADLE
    # ================================
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"

    # ================================
    # CHECK
    # ================================
    - name: Check
      run: ./gradlew check

    # ================================
    # TEST REPORT
    # ================================
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4.3.1
      if: success() || failure()
      with:
        report_paths: example/build/test-results/test/TEST-*.xml
        check_name: Test Report
        detailed_summary: true
        include_passed: true
        suite_regex: '*'
        check_title_template: "<strong>{{SUITE_NAME}}</strong> <code>{{TEST_NAME}}</code>"
